Move to new structure

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -20,14 +20,32 @@ jobs:
         with:
           dotnet-version: 8.0.x
 
-      - name: Install dependencies
-        run: dotnet restore
+      - name: Install dependencies with retry
+        run: |
+          retries=5
+          base_wait_time=15
+          exponent=2
+
+          for i in $(seq 1 $retries); do
+            if dotnet restore; then
+              break
+            fi
+
+            if [ $i -lt $retries ]; then
+              wait_time=$(awk "BEGIN {print int($base_wait_time * ($exponent ^ ($i - 1)))}")
+              echo "dotnet restore failed, retrying in $wait_time seconds..."
+              sleep $wait_time
+            else
+              echo "dotnet restore failed after $retries retries."
+              exit 1
+            fi
+          done
 
       - name: Build
         run: dotnet build --configuration Release --no-restore
 
       - name: Test
-        run: dotnet test test/Soenneker.Blazor.Masonry.Tests.csproj --no-restore --verbosity normal
+        run: dotnet test test/Soenneker.Blazor.Masonry.Tests/Soenneker.Blazor.Masonry.Tests.csproj --no-restore --verbosity normal
 
       - name: Pack
         run: dotnet pack --no-build --configuration Release --output .
